version: '3.8'
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: fitnessdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
